version: "3.9"

services:
  frontend-web:
    build:
      context: .
      target: dev
    command: bash -lc "sed -i 's/\\r$//' docker/dev-entrypoint.sh || true; bash docker/dev-entrypoint.sh"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PNPM_PROGRESS_BAR: "0"
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store
      - pnpm-node-modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  pnpm-store:
  pnpm-node-modules:

